" Examples
" - https://github.com/corps/nix-machines/blob/master/packages/vim/vimrc
" - https://github.com/shdpl/nixos-configuration/blob/master/data/.config/nvim/bundle/go/plugin/go.vim
colorscheme abstract

set autochdir
set autoindent
set hlsearch			" highlight search results
set ignorecase			" case insensitive searches
set laststatus=1		" only show statusbar if >1 windows open
set listchars=tab:>-,eol:$
set nowrap
set shortmess+=I		" disable welcome screen
set smartcase			" case-sensitive search only if specified
set splitright			" vsplit window to the right by default
set wildmenu			" dmenu-style menu
set wildmode=full

"" MAPS
"" See :h keycodes
let mapleader=","

nnoremap <leader>l :set list!<CR>
nnoremap <leader>r :source $MYVIMRC<CR>
nnoremap <leader>S :setlocal spell!<CR>
nnoremap <leader>v :e $MYVIMRC<CR>
nnoremap <leader>w :w !sudo tee %<CR><CR>

nnoremap <silent> <leader>g :Goyo<CR>
nnoremap <silent> <leader>n :NERDTreeToggle<CR>
nnoremap <silent> <leader>t :TagbarToggle<CR>

autocmd FileType yaml setlocal ai et sw=2 ts=2 cuc
autocmd FileType nix setlocal cuc
