format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    ${custom.k8s}\
    $kubernetes\
    $hg_branch\
    $docker_context\
    $package\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $java\
    $julia\
    $nim\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $crystal\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
"""

[golang]
symbol = " "

[kubernetes]
symbol = "☸ "
disabled = true

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

# Use this custom k8s module instead of built-in kubernetes module to
# avoid "prompt pollution" by only showing k8s context when in a
# relevant directory.
[custom.k8s]
command = "echo $(kubectl config current-context) ($(kubectl config view --minify --output 'jsonpath={..namespace}'))"
symbol = "☸ "
when = "[[ $PWD =~ k8s ]]"
