name: Lint PR

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # See https://github.com/amannn/action-semantic-pull-request#configuration
          types: |
            fix
            feat
            chore
            style
            docs
            refactor
            perf
            test
            build
            ci
            revert
