name: Test
on:
  pull_request:
    branches: [master]
jobs:
  main:
    strategy:
      matrix:
        # See https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os:
          - ubuntu-latest
          - macos-10.15 # Catalina

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup cachix
        uses: cachix/cachix-action@v8
        with:
          name: qjcg
          authToken: "${{ secrets.CACHIX_AUTHTOKEN }}"

      - name: Check nix formatting
        run: nix run nixpkgs#nixpkgs-fmt -- --check .

      - name: Check flake (`nix flake check`)
        run: nix flake check
